[package]
name = "service"
version = "0.1.0"
authors = ["Julio Monteiro <juliolrmonteiro@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
hdk = { git = "https://github.com/holochain/holochain-rust", branch = "release-0.0.8-alpha" }
holochain_wasm_utils = { git = "https://github.com/holochain/holochain-rust", branch = "release-0.0.8-alpha" }
holochain_core_types_derive = { git = "https://github.com/holochain/holochain-rust", branch = "release-0.0.8-alpha" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
