[package]
name = "service"
version = "0.0.3"
authors = ["Julio Monteiro <julio.monteiro@holo.host>"]
edition = "2018"

[dependencies]
serde = { version = "=1.0.89", features = ["rc"] }
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
syn = "=0.15.31"
hdk = { git = "https://github.com/holochain/holochain-rust", branch = "release-0.0.18-alpha1" }
holochain_wasm_utils = { git = "https://github.com/holochain/holochain-rust", branch = "release-0.0.18-alpha1" }
holochain_core_types_derive = { git = "https://github.com/holochain/holochain-rust", branch = "release-0.0.18-alpha1" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
