[package]
name = "service"
version = "0.0.2"
authors = ["Julio Monteiro <julio.monteiro@holo.host>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
hdk = { git = "https://github.com/holochain/holochain-rust", branch = "release-0.0.15-alpha1" }
holochain_wasm_utils = { git = "https://github.com/holochain/holochain-rust", branch = "release-0.0.15-alpha1" }
holochain_core_types_derive = { git = "https://github.com/holochain/holochain-rust", branch = "release-0.0.15-alpha1" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
