# -----------  Agents  -----------
# create keys with "hc keygen" and paste them here
[[agents]]
id = "main-agent"
name = "LoggerTester"
public_address = "<paste-address-here>"
keystore_file = "<paste-key-location-here>"

# -----------  DNA  -----------
[[dnas]]
id = "logger-dna"
file = "dist/servicelogger.dna.json"
hash = "QmZPz7JfxKHHdu6f1ywXU92xonkC9cNetUySWVJSp5F4DV"

[[dnas]]
id = "fuel-dna"
file = "dist/holofuel.dna.json"
hash = "QmZPz7JfxKHHdu6f1ywXU92xonkC9cNetUySWVJSp5F4DV"

[[dnas]]
id = "host-dna"
file = "dist/holohosting.dna.json"
hash = "QmZPz7JfxKHHdu6f1ywXU92xonkC9cNetUySWVJSp5F4DV"


[[instances]]
id = "holofuel-instance"
dna = "fuel-dna"
agent = "main-agent"
[instances.logger]
type = "simple"
# file = "fuel.log"
[instances.storage]
type = "memory"
# type = "file"
# path = "tmp-storage1"

[[instances]]
id = "logger-instance"
dna = "logger-dna"
agent = "main-agent"
[instances.logger]
type = "simple"
# file = "logger.log"
[instances.storage]
type = "memory"
# type = "file"
# path = "tmp-storage2"

[[instances]]
id = "host-instance"
dna = "host-dna"
agent = "main-agent"
[instances.logger]
type = "simple"
# file = "host.log"
[instances.storage]
type = "memory"
# type = "file"
# path = "tmp-storage2"


[[interfaces]]
id = "websocket-interface"
[interfaces.driver]
type = "websocket"
port = 3000 
[[interfaces.instances]]
id = "logger-instance"
[[interfaces.instances]]
id = "holofuel-instance"
[[interfaces.instances]]
id = "host-instance"


[[interfaces]]
id = "http-interface"
[interfaces.driver]
type = "http"
port = 4000
[[interfaces.instances]]
id = "logger-instance"
[[interfaces.instances]]
id = "holofuel-instance"
[[interfaces.instances]]
id = "host-instance"

[[bridges]]
caller_id = "logger-instance"
callee_id = "holofuel-instance"
handle = "holofuel-bridge"

[[bridges]]
caller_id = "logger-instance"
callee_id = "host-instance"
handle = "hosting-bridge"

# -----------  UI  -----------
[[ui_bundles]]
id = "main"
root_dir = "ui"
hash = "Qmjk0"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 8800
dna_interface = "websocket-interface"

[[ui_bundles]]
id = "holofuel-ui"
root_dir = "dist/holofuel-ui"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface2"
bundle = "holofuel-ui"
port = 8300
dna_interface = "websocket-interface"

[[ui_bundles]]
id = "holohost-ui"
root_dir = "dist/holohost-ui"
hash = "Qm001"

[[ui_interfaces]]
id = "ui-interface3"
bundle = "holohost-ui"
port = 8400
dna_interface = "websocket-interface"

# -----------  Networking  -----------
# [network]
# n3h_path = "/home/monteiro/src/n3h"
# n3h_persistence_path = "/tmp"
# bootstrap_nodes = []

# -----------  Networking instructions  -----------
# To get networking running requires the following steps:

# - Clone the repo for the holochain networking library n3h (https://github.com/holochain/n3h)
# - Checkout the tag in n3h for holochain v0.0.4-alpha (git fetch --tags && git checkout v0.0.4-alpha)
# - run `npm install && npm run boostrap` in the n3h directory
# - change the n3h_path above to point to the location where you cloned the repo

# - If you are the first node then start the conductor and take careful note of the line that
#	begins with `READY! tcp://127.0.0.1:43859 [...]
#	You will need to copy the contents of the array and send it to the nodes you plan to network with.
# - If you are a joining node then paste the contents from the first node in to the bootstrap_nodes field above
# - Make sure that you all have different agents for your instances (uncomment new agent and change the instances agent field)
# - Uncomment the network section and you should be ready do go!
