version: 2

jobs:
  # build is required
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: nixos/nix
    steps:
      - checkout
      - run: nix-shell --option substituters https://cache.holo.host --option trusted-public-keys cache.holo.host-1:lNXIXtJgS9Iuw4Cu6X0HINLu9sTfcjEntnrgwMQIMcE= --run 'make test'
