version: 2

jobs:
 # must be called build for local circle cli to work
 # is actually unit tests
 build:
  branches:
    only:
      - master
      - circleci
  docker:
   - image: holochain/holochain-rust:latest
  resource_class: medium
  steps:
   - checkout
   - run: nix-shell
   