version: 2

jobs:
  # build is required
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: holochain/holonix:latest
    steps:
      - checkout
      - run: nix-shell --run 'make test'
