version: 2

jobs:
  # build is required
  build:
    branches:
      only:
        - master
        - circleci
    docker:
      - image: holochain/holochain-rust:circle.01.warm.nix
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Holo ServiceLogger
          command: echo "starting CI for Holo ServiceLogger"
      - run:
          name: nix-shell
          command: |
            nix-shell --packages gnumake --packages rustup --packages rustc --packages cargo --run 'make test'
          no_output_timeout: 45m
